#!/usr/bin/env bash
# To install Cutadapt: python3 -m pip install --user --upgrade cutadapt
# To run Cutadapt (must include full path): ~/.local/bin/cutadapt --version

#load cutadapt
~/.local/bin/cutadapt --version

#define variables for the primers (strings)
#overhand regions have been removed from the primer sequences
#TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG for the forward primers
#GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG for the reverse primers

firstPrimer_F="CCTACGGGNGGCWGCAG"
firstPrimer_R="GACTACHVGGGTATCTAATCC"

secondPrimer_F="NCCTACGGGNGGCWGCAG"
secondPrimer_R="NGACTACHVGGGTATCTAATCC"

thirdPrimer_F="NNCCTACGGGNGGCWGCAG"
thirdPrimer_R="NNGACTACHVGGGTATCTAATCC"

fourthPrimer_F="NNNCCTACGGGNGGCWGCAG"
fourthPrimer_R="NNNGACTACHVGGGTATCTAATCC"

#run cutadapt using all 4 forward and reverse primers by calling the variables
#for i in range 075 to 149
#do cutadapt for both forward and reverse ERR5924${i} reads
#loops iterate through all files in the CopyOfKoreanSkincareRawSequenceData folder

#option a
for i in $(seq 075 149)
do 
  ~/.local/bin/cutadapt -a $firstPrimer_F -a $secondPrimer_F -a $thirdPrimer_F -a $fourthPrimer_F \
  -A $firstPrimer_R -A $secondPrimer_R -A $thirdPrimer_R -A $fourthPrimer_R \
  -o KoreanSkincareTrimmedReads_a/Trimmed_ERR5924${i}_Illumina_MiSeq_paired_end_sequencing_1.fastq.gz \
  -p KoreanSkincareTrimmedReads_a/Trimmed_ERR5924${i}_Illumina_MiSeq_paired_end_sequencing_2.fastq.gz \
  CopyOfKoreanSkincareRawSequenceData/ERR5924${i}_Illumina_MiSeq_paired_end_sequencing_1.fastq.gz \
  CopyOfKoreanSkincareRawSequenceData/ERR5924${i}_Illumina_MiSeq_paired_end_sequencing_2.fastq.gz
done

#option g
for i in $(seq 075 149)
do 
  ~/.local/bin/cutadapt -g $firstPrimer_F -g $secondPrimer_F -g $thirdPrimer_F -g $fourthPrimer_F \
  -G $firstPrimer_R -G $secondPrimer_R -G $thirdPrimer_R -G $fourthPrimer_R \
  -o KoreanSkincareTrimmedReads_g/Trimmed_ERR5924${i}_Illumina_MiSeq_paired_end_sequencing_1.fastq.gz \
  -p KoreanSkincareTrimmedReads_g/Trimmed_ERR5924${i}_Illumina_MiSeq_paired_end_sequencing_2.fastq.gz \
  CopyOfKoreanSkincareRawSequenceData/ERR5924${i}_Illumina_MiSeq_paired_end_sequencing_1.fastq.gz \
  CopyOfKoreanSkincareRawSequenceData/ERR5924${i}_Illumina_MiSeq_paired_end_sequencing_2.fastq.gz
done
